name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.10
    with:
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx run-many --all --target=test --parallel=3 --ci --code-coverage --coverageReporters=lcov
        npx nx affected --target=build --parallel=3
      final-commands: |
        npx nx-cloud record node ./tools/scripts/coverageMerger.js
      artifacts-path: |
        coverage/lcov.info
      artifacts-name: coverage-report

  sonar:
    name: SonarCloud
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: download source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.10
    with:
      number-of-agents: 3
